<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\images\Categorias\**" />
    <Compile Remove="wwwroot\images\Llantas\**" />
    <Compile Remove="wwwroot\images\Perfiles\**" />
    <Compile Remove="wwwroot\images\Productos\**" />
    <Compile Remove="wwwroot\images\Promociones\**" />
    <Compile Remove="wwwroot\images\Servicios\**" />
    <Content Remove="wwwroot\images\Categorias\**" />
    <Content Remove="wwwroot\images\Llantas\**" />
    <Content Remove="wwwroot\images\Perfiles\**" />
    <Content Remove="wwwroot\images\Productos\**" />
    <Content Remove="wwwroot\images\Promociones\**" />
    <Content Remove="wwwroot\images\Servicios\**" />
    <EmbeddedResource Remove="wwwroot\images\Categorias\**" />
    <EmbeddedResource Remove="wwwroot\images\Llantas\**" />
    <EmbeddedResource Remove="wwwroot\images\Perfiles\**" />
    <EmbeddedResource Remove="wwwroot\images\Productos\**" />
    <EmbeddedResource Remove="wwwroot\images\Promociones\**" />
    <EmbeddedResource Remove="wwwroot\images\Servicios\**" />
    <None Remove="wwwroot\images\Categorias\**" />
    <None Remove="wwwroot\images\Llantas\**" />
    <None Remove="wwwroot\images\Perfiles\**" />
    <None Remove="wwwroot\images\Productos\**" />
    <None Remove="wwwroot\images\Promociones\**" />
    <None Remove="wwwroot\images\Servicios\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Abstractions" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Rotativa.AspNetCore" Version="1.4.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="2.1.8" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="wwwroot\images\productoos\" />
  </ItemGroup>

</Project>
