// <auto-generated />
using System;
using Llanteria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Llanteria.Migrations
{
    [DbContext(typeof(LlanteriaDbContext))]
    partial class LlanteriaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Llanteria.Models.Bodega", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CapacidadMaxima")
                        .HasColumnType("int");

                    b.Property<string>("NombreBodega")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Ubicacion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Bodegas__3214EC07D99D647E");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("Llanteria.Models.CanjeIncentivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EntregadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaCanje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdIncentivo")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__CanjeInc__3214EC0748C92D09");

                    b.HasIndex("EntregadoPor");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdIncentivo");

                    b.ToTable("CanjeIncentivos");
                });

            modelBuilder.Entity("Llanteria.Models.CatalogoIncentivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombrePremio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PuntosRequeridos")
                        .HasColumnType("int");

                    b.Property<int?>("StockDisponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id")
                        .HasName("PK__Catalogo__3214EC07BD55A4C5");

                    b.ToTable("CatalogoIncentivos");
                });

            modelBuilder.Entity("Llanteria.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Categori__3214EC07A3F49746");

                    b.ToTable("CategoriaGasto", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int>("IdSexo")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PuntosAcumulados")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Clientes__3214EC070B0B0CAC");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdSexo");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Llanteria.Models.DetalleFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("CodigoItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripción")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__DetalleF__3214EC07183BE331");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdServicio");

                    b.ToTable("DetalleFactura", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.DetalleProducto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ancho")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Diametro")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("GarantiaMeses")
                        .HasColumnType("int");

                    b.Property<int>("IdMarca")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<string>("IndiceCarga")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("IndiceVelocidad")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Perfil")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TipoAceite")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Viscosidad")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__DetalleP__3214EC077517B69D");

                    b.HasIndex("IdMarca");

                    b.HasIndex(new[] { "IdProducto" }, "UQ__DetalleP__09889211BCD1C267")
                        .IsUnique();

                    b.ToTable("DetalleProductos");
                });

            modelBuilder.Entity("Llanteria.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Correo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<byte[]>("Foto")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Horario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdDocumento")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<int>("IdSexo")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salario")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Empleado__3214EC07434BD29A");

                    b.HasIndex("IdDocumento");

                    b.HasIndex("IdRol");

                    b.HasIndex("IdSexo");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Llanteria.Models.EstadoInventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EstadoIn__3214EC075355F3A3");

                    b.ToTable("EstadoInventario", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Fecha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Iva")
                        .HasColumnType("decimal(18, 2)")
                        .HasColumnName("IVA");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("RteFte")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalBruto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Facturas__3214EC070AD40338");

                    b.HasIndex("IdCliente");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Llanteria.Models.Gasto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivoSupport")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pendiente");

                    b.Property<DateOnly?>("FechaPago")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Gastos__3214EC0735B1CBF7");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Llanteria.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CantidadIngresada")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("FechaIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdBodega")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("StockActual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("StockMinimo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(40);

                    b.HasKey("Id")
                        .HasName("PK__Inventar__3214EC0732C7DFFF");

                    b.HasIndex("IdBodega");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdProducto");

                    b.HasIndex(new[] { "Codigo" }, "UQ__Inventar__06370DAC43C451B2")
                        .IsUnique();

                    b.ToTable("Inventario", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.LogActividad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DireccionIp")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DireccionIP");

                    b.Property<DateTime?>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TablaAfectada")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__LogActiv__3214EC078ACEF574");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LogActividad", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.Marca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Marcas__3214EC07BCD148E3");

                    b.ToTable("Marcas");
                });

            modelBuilder.Entity("Llanteria.Models.Oferta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoPromocional")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("MontoDescuentoFijo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal?>("PorcentajeDescuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Ofertas__3214EC078BED32FB");

                    b.HasIndex(new[] { "CodigoPromocional" }, "UQ__Ofertas__172ECB7A9611BA9C")
                        .IsUnique()
                        .HasFilter("[CodigoPromocional] IS NOT NULL");

                    b.ToTable("Ofertas");
                });

            modelBuilder.Entity("Llanteria.Models.PerfilUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<byte[]>("FotoCircular")
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool?>("NotificacionesActivas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("TemaPreferencia")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Light");

                    b.HasKey("Id")
                        .HasName("PK__PerfilUs__3214EC077EF3D8F5");

                    b.HasIndex(new[] { "IdUsuario" }, "UQ__PerfilUs__5B65BF964D23691B")
                        .IsUnique();

                    b.ToTable("PerfilUsuario", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categoria")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdBodega")
                        .HasColumnType("int");

                    b.Property<int>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PrecioCompra")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<string>("RutaImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Producto__3214EC07A32D7B2F");

                    b.HasIndex("IdBodega");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Llanteria.Models.Proveedore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NombreEmpresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Proveedo__3214EC0795DE5AE5");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Llanteria.Models.RecuperacionCuenta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TokenRecuperacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Usado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id")
                        .HasName("PK__Recupera__3214EC078147DB11");

                    b.HasIndex("IdUsuario");

                    b.ToTable("RecuperacionCuentas");
                });

            modelBuilder.Entity("Llanteria.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Roles__3214EC07D0A9A948");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Llanteria.Models.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Sexo__3214EC0792275EF0");

                    b.ToTable("Sexo", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id")
                        .HasName("PK__TipoDocu__3214EC07071BF407");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.TipoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IconoPath")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("ValorServicio")
                        .HasColumnType("decimal(16, 3)");

                    b.HasKey("Id")
                        .HasName("PK__TipoServ__3214EC0792BBB127");

                    b.ToTable("TipoServicio", (string)null);
                });

            modelBuilder.Entity("Llanteria.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Activo");

                    b.Property<DateTime?>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("FechaFinBaneo")
                        .HasColumnType("datetime");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("MotivoSancion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimaConexion")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Usuarios__3214EC07440B1D54");

                    b.HasIndex("IdRol");

                    b.HasIndex(new[] { "Username" }, "UQ__Usuarios__536C85E49A6A20E7")
                        .IsUnique();

                    b.HasIndex(new[] { "IdEmpleado" }, "UQ__Usuarios__CE6D8B9F67398071")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Llanteria.Models.Vehiculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id")
                        .HasName("PK__Vehiculo__3214EC07EB4BB1DF");

                    b.HasIndex("IdCliente");

                    b.ToTable("Vehiculos");
                });

            modelBuilder.Entity("Llanteria.Models.CanjeIncentivo", b =>
                {
                    b.HasOne("Llanteria.Models.Usuario", "EntregadoPorNavigation")
                        .WithMany("CanjeIncentivos")
                        .HasForeignKey("EntregadoPor")
                        .IsRequired()
                        .HasConstraintName("FK_Canje_Usuario");

                    b.HasOne("Llanteria.Models.Cliente", "IdClienteNavigation")
                        .WithMany("CanjeIncentivos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Canje_Cliente");

                    b.HasOne("Llanteria.Models.CatalogoIncentivo", "IdIncentivoNavigation")
                        .WithMany("CanjeIncentivos")
                        .HasForeignKey("IdIncentivo")
                        .IsRequired()
                        .HasConstraintName("FK_Canje_Incentivo");

                    b.Navigation("EntregadoPorNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdIncentivoNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Cliente", b =>
                {
                    b.HasOne("Llanteria.Models.TipoDocumento", "IdDocumentoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdDocumento")
                        .IsRequired()
                        .HasConstraintName("FK_Clientes_Documento");

                    b.HasOne("Llanteria.Models.Sexo", "IdSexoNavigation")
                        .WithMany("Clientes")
                        .HasForeignKey("IdSexo")
                        .IsRequired()
                        .HasConstraintName("FK_Clientes_Sexo");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdSexoNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.DetalleFactura", b =>
                {
                    b.HasOne("Llanteria.Models.Factura", "IdFacturaNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdFactura")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleF_Factura");

                    b.HasOne("Llanteria.Models.Producto", "IdProductoNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdProducto")
                        .HasConstraintName("FK_DetalleF_Producto");

                    b.HasOne("Llanteria.Models.TipoServicio", "IdServicioNavigation")
                        .WithMany("DetalleFacturas")
                        .HasForeignKey("IdServicio")
                        .HasConstraintName("FK_DetalleF_Servicio");

                    b.Navigation("IdFacturaNavigation");

                    b.Navigation("IdProductoNavigation");

                    b.Navigation("IdServicioNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.DetalleProducto", b =>
                {
                    b.HasOne("Llanteria.Models.Marca", "IdMarcaNavigation")
                        .WithMany("DetalleProductos")
                        .HasForeignKey("IdMarca")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleP_Marca");

                    b.HasOne("Llanteria.Models.Producto", "IdProductoNavigation")
                        .WithOne("DetalleProducto")
                        .HasForeignKey("Llanteria.Models.DetalleProducto", "IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_DetalleP_Producto");

                    b.Navigation("IdMarcaNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Empleado", b =>
                {
                    b.HasOne("Llanteria.Models.TipoDocumento", "IdDocumentoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdDocumento")
                        .IsRequired()
                        .HasConstraintName("FK_Empleados_Documento");

                    b.HasOne("Llanteria.Models.Role", "IdRolNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Empleados_Roles");

                    b.HasOne("Llanteria.Models.Sexo", "IdSexoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("IdSexo")
                        .IsRequired()
                        .HasConstraintName("FK_Empleados_Sexo");

                    b.Navigation("IdDocumentoNavigation");

                    b.Navigation("IdRolNavigation");

                    b.Navigation("IdSexoNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Factura", b =>
                {
                    b.HasOne("Llanteria.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Facturas_Cliente");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Gasto", b =>
                {
                    b.HasOne("Llanteria.Models.CategoriaGasto", "IdCategoriaNavigation")
                        .WithMany("Gastos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired()
                        .HasConstraintName("FK_Gastos_Categoria");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Inventario", b =>
                {
                    b.HasOne("Llanteria.Models.Bodega", "IdBodegaNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdBodega")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Bodega");

                    b.HasOne("Llanteria.Models.EstadoInventario", "IdEstadoNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdEstado")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Estado");

                    b.HasOne("Llanteria.Models.Producto", "IdProductoNavigation")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdProducto")
                        .IsRequired()
                        .HasConstraintName("FK_Inventario_Producto");

                    b.Navigation("IdBodegaNavigation");

                    b.Navigation("IdEstadoNavigation");

                    b.Navigation("IdProductoNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.LogActividad", b =>
                {
                    b.HasOne("Llanteria.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("LogActividads")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Log_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.PerfilUsuario", b =>
                {
                    b.HasOne("Llanteria.Models.Usuario", "IdUsuarioNavigation")
                        .WithOne("PerfilUsuario")
                        .HasForeignKey("Llanteria.Models.PerfilUsuario", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Perfil_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Producto", b =>
                {
                    b.HasOne("Llanteria.Models.Bodega", "BodegaNavigation")
                        .WithMany()
                        .HasForeignKey("IdBodega")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Llanteria.Models.Proveedore", "IdProveedorNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .IsRequired()
                        .HasConstraintName("FK_Productos_Proveedor");

                    b.Navigation("BodegaNavigation");

                    b.Navigation("IdProveedorNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.RecuperacionCuenta", b =>
                {
                    b.HasOne("Llanteria.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("RecuperacionCuenta")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Recuperacion_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Usuario", b =>
                {
                    b.HasOne("Llanteria.Models.Empleado", "IdEmpleadoNavigation")
                        .WithOne("Usuario")
                        .HasForeignKey("Llanteria.Models.Usuario", "IdEmpleado")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Empleado");

                    b.HasOne("Llanteria.Models.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired()
                        .HasConstraintName("FK_Usuarios_Rol");

                    b.Navigation("IdEmpleadoNavigation");

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("Llanteria.Models.Vehiculo", b =>
                {
                    b.HasOne("Llanteria.Models.Cliente", "Cliente")
                        .WithMany("Vehiculos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Vehiculos_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Llanteria.Models.Bodega", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Llanteria.Models.CatalogoIncentivo", b =>
                {
                    b.Navigation("CanjeIncentivos");
                });

            modelBuilder.Entity("Llanteria.Models.CategoriaGasto", b =>
                {
                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("Llanteria.Models.Cliente", b =>
                {
                    b.Navigation("CanjeIncentivos");

                    b.Navigation("Facturas");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Llanteria.Models.Empleado", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Llanteria.Models.EstadoInventario", b =>
                {
                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Llanteria.Models.Factura", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("Llanteria.Models.Marca", b =>
                {
                    b.Navigation("DetalleProductos");
                });

            modelBuilder.Entity("Llanteria.Models.Producto", b =>
                {
                    b.Navigation("DetalleFacturas");

                    b.Navigation("DetalleProducto");

                    b.Navigation("Inventarios");
                });

            modelBuilder.Entity("Llanteria.Models.Proveedore", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Llanteria.Models.Role", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Llanteria.Models.Sexo", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Llanteria.Models.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("Llanteria.Models.TipoServicio", b =>
                {
                    b.Navigation("DetalleFacturas");
                });

            modelBuilder.Entity("Llanteria.Models.Usuario", b =>
                {
                    b.Navigation("CanjeIncentivos");

                    b.Navigation("LogActividads");

                    b.Navigation("PerfilUsuario");

                    b.Navigation("RecuperacionCuenta");
                });
#pragma warning restore 612, 618
        }
    }
}
